# Generated by Django 4.2.5 on 2023-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisManagementAssistant', '0002_remove_cmdoc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdoc',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmdoc',
            name='fileName',
            field=models.CharField(default='', max_length=120),
        ),
    ]
