# Generated by Django 4.2.5 on 2023-09-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisManagementAssistant', '0003_cmdoc_slug_alter_cmdoc_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdoc',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
