# Generated by Django 4.2.5 on 2023-09-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crisisManagementAssistant', '0005_cmdoc_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmdoc',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='cmdoc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
