# Generated by Django 4.2.5 on 2023-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisManagementAssistant', '0006_rename_uploaded_at_cmdoc_timestamp_alter_cmdoc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdoc',
            name='file',
            field=models.FileField(default='', upload_to='cmdocs/'),
        ),
    ]
