# Generated by Django 4.2.5 on 2023-12-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisManagementAssistant', '0008_cmdoc_extractdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdoc',
            name='group',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cmdoc',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
