# Generated by Django 4.2.5 on 2023-12-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisManagementAssistant', '0009_cmdoc_group_alter_cmdoc_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdoc',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
