# Generated by Django 4.2.5 on 2024-01-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisManagementAssistant', '0011_remove_cmdoc_group_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdoc',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
