# Generated by Django 4.2.5 on 2024-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crisisManagementAssistant', '0012_alter_cmdoc_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdoc',
            name='fileName',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
